"""criacao inicial das tabelas

Revision ID: 753af9d88168
Revises: 
Create Date: 2026-09-29 12:46:53.193608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753af9d88168'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nacionalidade', sa.String(length=150), nullable=True),
    sa.Column('estado_civil', sa.String(length=150), nullable=True),
    sa.Column('profissao', sa.String(length=150), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('cidade', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=150), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('evento',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=False),
    sa.Column('horario_evento', sa.Time(), nullable=False),
    sa.Column('nome_local', sa.String(length=100), nullable=False),
    sa.Column('endereco_local', sa.String(length=500), nullable=False),
    sa.Column('numero_convidados', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('documento',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=100), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('drive_url', sa.String(length=255), nullable=True),
    sa.Column('data_geracao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id_evento'], ),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('proposta',
    sa.Column('id_proposta', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('valor_decoracao', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_moveis', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_adicionais', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('condicao_pagamento', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id_evento'], ),
    sa.PrimaryKeyConstraint('id_proposta')
    )
    op.create_table('contrato',
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_proposta', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_assinatura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id_evento'], ),
    sa.ForeignKeyConstraint(['id_proposta'], ['proposta.id_proposta'], ),
    sa.PrimaryKeyConstraint('id_contrato'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('item_proposta',
    sa.Column('id_item_proposta', sa.Integer(), nullable=False),
    sa.Column('id_proposta', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('opcional', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_proposta'], ['proposta.id_proposta'], ),
    sa.PrimaryKeyConstraint('id_item_proposta')
    )
    op.create_table('parcela',
    sa.Column('id_parcela', sa.Integer(), nullable=False),
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_contrato'], ['contrato.id_contrato'], ),
    sa.PrimaryKeyConstraint('id_parcela')
    )
    op.create_table('pagamento',
    sa.Column('id_pagamento', sa.Integer(), nullable=False),
    sa.Column('id_parcela', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_parcela'], ['parcela.id_parcela'], ),
    sa.PrimaryKeyConstraint('id_pagamento')
    )
    op.create_table('recibo',
    sa.Column('id_recibo', sa.Integer(), nullable=False),
    sa.Column('id_pagamento', sa.Integer(), nullable=False),
    sa.Column('numero_recibo', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pagamento'], ['pagamento.id_pagamento'], ),
    sa.PrimaryKeyConstraint('id_recibo'),
    sa.UniqueConstraint('numero_recibo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recibo')
    op.drop_table('pagamento')
    op.drop_table('parcela')
    op.drop_table('item_proposta')
    op.drop_table('contrato')
    op.drop_table('proposta')
    op.drop_table('documento')
    op.drop_table('evento')
    op.drop_table('usuario')
    op.drop_table('cliente')
    # ### end Alembic commands ###
